nonebot_plugin_clovers = "{\"plugins_path\": \"./clovers_library\", \"plugins_list\": []}"

["plugins.nonebot_plugin_clovers"]
plugins_path = "./clovers_library"
plugins_list = []

[clovers]
plugins_path = "./clovers_library"
plugins_list = []
